name: allTheBasics
version: '${project.version}'
main: com.sieadev.allthebasics.AllTheBasics
api-version: 1.20
author: sieadev
description: All the basics your minecraft Server needs
permissions:
  atb:
    children:
      gamemode:
        children:
          creative:
            description: use /gm creative
          spectator:
            description: use /gm spectator
          survival:
            description: use /gm survival
          adventure:
            description: use /gm adventure
      chat:
        children:
          color:
            description: use colorful text in chat
          highlightNumbers:
            description: auto-highlight numbers
          math:
            description: auto-calculate math
          emoji:
            description: auto-convert emojis
      fakeop:
        description: use /fakeop
      heal:
        description: use /healPlayer
      feed:
        description: use /feed
      fly:
        description: use /fly
      freeze:
        description: use /freeze
      teleport:
        description: use /tp
      vanish:
        description: use /vanish
      disguise:
        description:  use /disguise
      timer:
        children:
            start:
              descrption: use /timer start
            stop:
              descrption: use /timer stop
      burn:
        description: use /burn
      suicide:
        description: use /suicide
      kickall:
        description: use /kickall
      kickplayer:
        description: use /kickplayer
      home:
        children:
          set:
            descrption: use /sethome
          find:
            description: use /findhome
          teleport:
            description: use /home

commands:
  heal:
    permission: atb.heal
    usage: /heal <player>
    description: Heal a player
    alias: h
  feed:
    permission: atb.feed
    usage: /heal <player>
    description: Feed a player
    alias: f
  fakeop:
    permission: atb.fakeop
    usage: /fakeop <player>
    description: Give a player fake OP
  timer:
    permission: atb.timer
    usage: /timer <start/stop>
    description: Starts or stops a personal timer for a player
  freeze:
    permission: atb.freeze
    usage: /freeze <target>
    description: Freeze a player
  fly:
    permission: atb.fly
    usage: /fly
    description: Enables flying
  disguise:
    permission: atb.disguise
    usage: /disguise
    description: Disguise as a player
  vanish:
    permission: atb.vanish
    usage: /vanish
    description: Become invisible
  tp:
    permission: atb.teleport
    usage: /teleport <player>
    description: Teleport to a player // Teleport a player to a player
    alias: teleport
  gm:
    permissions: [atb.gamemode.creative, atb.gamemode.survival, atb.gamemode.adventure, atb.gamemode.spectator]
    usage: gm <gamemode>
    description: Change your Gamemmode
    alias: gamemode
  gm0:
    permission: atb.gamemode.survival
    usage: /gm1
    description: Change your Gamemode to survival
  gm1:
    permission: atb.gamemode.creative
    usage: /gm1
    description: Change your Gamemode to creative
  gm2:
    permission: atb.gamemode.adventure
    usage: /gm1
    description: Change your Gamemode to adventure
  gm3:
    permission: atb.gamemode.spectator
    usage: /gm1
    description: Change your Gamemode to spectator
  burn:
    permission: atb.burn
    usage: /burn <player>
    description: Light a Player on fire
  suicide:
    permission: atb.suicide
    usage: /suicide
    description: Kill yourself
  kickall:
    permission: atb.kickall
    usage: /kickall
    description: Kick all Players
  home:
    permissions: [atb.home.teleport, atb.home.find]
    usage: /home
    description: Teleport home
  findhome:
    permission: atb.home.find
    usage: /findhome
    description: Find your home
  sethome:
    permission: atb.home.set
    usage: /sethome
    description: Set your home